<?php
/**
 * Copyright © Batoh Andrii, All rights reserved.
 * See COPYING.txt for license details.
 * @author Yevhenii Hanzha <evgenijganza369@gmail.com>
 */
/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link">
    <a class="customer-link" <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>><i class="fa fa-user"></i>
    </a>
</li>
